<div class="grid_8">

<p>During 2007-9, the University of Lincoln led the HEFCE-funded <a href="http://learninglandscapes.lincoln.ac.uk/">Learning Landscapes project</a> which offered "the higher education community a practical and conceptual framework to consider the ways in which learning and teaching spaces are being designed and developed." The Learning Landscape project provided 12 case studies of different UK universities that had recently designed and built new learning spaces, as well as a set of 'development tools' to support the inclusive work of designing effective learning spaces between academics, support services, other key stakeholders and students. The project acknowledged the essential role of technology in the design of the learning landscape, as well as recognising the extent to which the Internet has disrupted and extended our understanding of what constitutes a learning space. The remit of the Learning Landscapes project was very much focused on the communicative process between different stakeholders around the construction of physical space and the extent to which technology might alter and enhance our understanding of spatiality.</p>

<p>With the Linking You project, we've attempted to draw from the recommendations of our earlier project and consider in much more detail one aspect of what might be called the 'virtual learning landscape' but we would argue is as <em>real</em> and as <em>valuable</em> to the work of Higher Education Institutions as the physical real estate. In our project, we understand technology not as an enhancement to the learning landscape but intrinsic to it (<a href="http://www.sfu.ca/~andrewf/pub_Questioning_Technology.html">Feenberg 1999</a>). This has always been the case (<a href="http://www.continuumbooks.com/CompanionWebsites/book-homepage.aspx?BookId=158591">Selwyn 2011</a>) but with the development of the Internet, we've tended to understand this particular set of technologies as something apart from the physical world, something 'virtual' and therefore somehow secondary - an after thought.</p>

<p>The overall output of the Linking You project is this toolkit, a plugin to the original Learning Landscapes project tools, which is meant to both support and facilitate a better understanding of institutional URIs and act as a focal point for both technical and non-technical stakeholders. We want you to trash your notions of the 'virtual', <em>get real</em> with URIs and understand their intrinsic role in developing and managing a contemporary university. We hope this is a toolkit that will help you reverse engineer <strong>.ac.uk</strong> and <em>imagineer</em> your domain in terms of the very <em>idea of the university</em>.</p>

<p>When talking about something as complex as 'the university' we're assuming that we understand what a university is <em>for</em>. The Learning Landscapes project tools have been useful to us in providing context to our specific task of examining the use and value of URIs in the university sector. The first tool challenges us to re-imagine higher education through an understanding of the history of the idea of the university. In other words, <em>know your domain</em>. Looking backwards at the idea of the university is referred to as a process of 'reverse imagineering', an idea influenced by the practice of 'reverse engineering' software, and this is something we have attempted to do through the comparative study of 40 institutions' and then the development of a proposed model of best practice.</p>

<p>In the current climate, as universities face difficult financial and ideological challenges, the idea and ideal of the university is being increasingly questioned. Today's university retains traces of its long history and this is no less apparent in the way that HEI's organise their resources and construct their URIs. The distinction first made 200 years ago between teaching and research is retained today and despite <a href="http://studentasproducer.lincoln.ac.uk/">efforts</a> to integrate these two core activities of the university, institutional websites clearly separate the two and more often than not reflect the increasing merger of research and enterprise. This is no surprise in the age of the 'entrepreneurial university', but would it be so strange for our institutional URIs to act as sign-posts across another space-time dimension of the campus, with the potential to extend our traditional collegiality to the so-called 'edgeless university'? (<a href="http://www.demos.co.uk/publications/the-edgeless-university">DEMOS 2009</a>) Taking this point of view, the mirroring of the physical structure of the university onto the web architecture of the institution can be understood as a rational but limited approach to the use of the web, reinforcing the idea that web development is simply an enhancement activity rather than an opportunity to re-architect university space-time. </p>

<p>Is it any surprise that institutional URI schemes so closely reflect the idea of the university that has developed since the medieval period? If, as Malcolm Bradbury wrote in the 1970s, the modern campus is so lacking distinction that it could just as easily serve as a prison, factory or shopping precinct, are our institutional websites condemned to the same indeterminate features? If the idea of the university is in danger of being lost, can it be re-asserted through the new spatially of the Internet, which feels like an exponential "annihilation of space by time", (<a href="http://www.marxists.org/archive/marx/works/1857/grundrisse/ch10.htm">Marx, Grundrisse Ch. 10</a>) when the economy of <em>land</em>, so ingrained in our conception of the world, seems barely relevant to the architecture of the web, but reveals itself continually in debates around Intellectual Property and copyright. No wonder that the avant-garde of web architecture is the 'open web', the 'web of data', whose proponents in just the past couple of years have increasingly argued for public domain licensing (e.g. <a href="http://creativecommons.org/choose/zero/">CC0</a>, <a href="http://www.opendatacommons.org/licenses/pddl/">PDDL</a>) and the effective abandonment of property as the organising principle of the web.</p> 

<p>This new space - cyberspace - allows for a new science of space, a <em>spatiology</em> that allows us to think critically and imaginatively about the idea and form of university we desire. We discussed this in the Learning Landscapes project, highlighting how critical pedagogy can be used as a design principle, a resource in the design and construction of a counter-space, providing critical tools with which we reverse imagineer the university. Cyberspace allows for 'Utopian thinking' through which the constraints of property rights, and the traditional hierarchies of research, teaching and learning become "manifest as entirely different spatial forms and temporal rhythms." (Harvey, <a href="http://books.google.co.uk/books?id=W00VHZg3u2MC">Space of Hope</a>, 2000, 237-8) Arguably, we're already seeing this Utopian thinking in the forms of the Open Data, Open Access and Open Education movements. This was recognised two years ago by JISC in the <a href="http://www.jisc.ac.uk/events/2009/06/demoslaunch.aspx">Edgeless University</a> report and it's time that the foresight of these critical movements shifts into the mainstream and their Utopianism infects the whole of .ac.uk. How do we begin to do it? Read our <a href="http://lncn.eu/toolkit/recommendations">recommendations</a>.</p>
</div>


<div class="grid_4 last">
<div class="box bg_light">

<div><blockquote>"What, design a URI? I have to design URIs? Yes, you have to think about it." <a href="http://www.w3.org/Provider/Style/URI">Berners-Lee 1998 W3C Style. Cool URIs don't change.</a></blockquote></div>

<div><blockquote>And now the campus is massive, one of those dominant modern environments of multi-functionality that modern man creates: close it down as a university…and you could open it again as a factory, a prison, a shopping precinct. (Malcolm Bradbury, <a href="http://books.google.co.uk/books?id=C1fqVSTHTHAC">The History Man</a>, 1975, 69)</blockquote></div>

<div>
<blockquote>The logic of digital technology leads us in a new direction. Objects, as well as ideas, are no longer fixed, no longer tangible. In cyberspace, there is no weight, no dimensions; structure is dynamic and changing; size is both infinite and immaterial. In this space, stories are written that change with each new reader; new material can be added, and old material can be deleted. Nothing is permanent. <em>Don't Fence Me In: Copyright, Property and Technology</em>, Kleinman (<a href="http://books.google.com/books?id=7P9oAAAAIAAJ">1996, 76</a>)
</blockquote>
</div>
</div>
</div>
